import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  athletes: defineTable({
    tokenIdentifier: v.string(),
    workosUserId: v.string(),
    displayName: v.string(),
    timezone: v.string(),
    units: v.union(v.literal("metric"), v.literal("imperial")),
    aiConsent: v.boolean(),
    analyticsConsent: v.boolean(),
    consentUpdatedAt: v.number(),
    onboarded: v.boolean(),
    status: v.union(v.literal("active"), v.literal("deleting")),
    createdAt: v.number(),
    thresholds: v.optional(v.any()),
    dashboard: v.optional(v.array(v.string())),
    hiddenWidgets: v.optional(v.array(v.string())),
    insightConsent: v.optional(v.boolean()),
  })
    .index("by_identity", ["tokenIdentifier"])
    .index("by_workos_user", ["workosUserId"]),
  auditEvents: defineTable({
    athleteId: v.id("athletes"),
    action: v.string(),
    at: v.number(),
  }).index("by_athlete", ["athleteId", "at"]),
  activities: defineTable({
    athleteId: v.id("athletes"),
    title: v.string(),
    sport: v.string(),
    start: v.number(),
    duration: v.number(),
    distance: v.optional(v.number()),
    summary: v.any(),
    metrics: v.any(),
    route: v.array(v.array(v.number())),
    streamKey: v.string(),
    sourceId: v.id("sources"),
    notes: v.string(),
    tags: v.array(v.string()),
    gearIds: v.array(v.id("gear")),
    excludedRecords: v.boolean(),
    version: v.string(),
    createdAt: v.number(),
    duplicateOf: v.optional(v.id("activities")),
    mergedInto: v.optional(v.id("activities")),
  }).index("by_athlete", ["athleteId", "start"]),
  sources: defineTable({
    athleteId: v.id("athletes"),
    name: v.string(),
    key: v.string(),
    hash: v.optional(v.string()),
    bytes: v.number(),
    status: v.string(),
    error: v.optional(v.string()),
    attempts: v.number(),
    createdAt: v.number(),
    activityId: v.optional(v.id("activities")),
    parentId: v.optional(v.id("sources")),
    parserVersion: v.optional(v.string()),
    childIds: v.optional(v.array(v.id("sources"))),
    completedChildren: v.optional(v.number()),
    failedChildren: v.optional(v.number()),
    importMetadata: v.optional(v.any()),
  })
    .index("by_athlete", ["athleteId", "createdAt"])
    .index("by_hash", ["athleteId", "hash"]),
  metricHistory: defineTable({
    athleteId: v.id("athletes"),
    activityId: v.id("activities"),
    metrics: v.any(),
    at: v.number(),
  })
    .index("by_athlete", ["athleteId"])
    .index("by_activity", ["activityId", "at"]),
  gear: defineTable({
    athleteId: v.id("athletes"),
    name: v.string(),
    kind: v.string(),
    retired: v.boolean(),
    maintenanceKm: v.optional(v.number()),
    maintenanceHours: v.optional(v.number()),
    servicedAt: v.number(),
  }).index("by_athlete", ["athleteId"]),
  goals: defineTable({
    athleteId: v.id("athletes"),
    title: v.string(),
    kind: v.string(),
    target: v.number(),
    start: v.number(),
    end: v.number(),
    manualProgress: v.optional(v.number()),
  }).index("by_athlete", ["athleteId"]),
  plans: defineTable({
    athleteId: v.id("athletes"),
    title: v.string(),
    sport: v.string(),
    start: v.number(),
    duration: v.number(),
    description: v.string(),
    intensity: v.optional(v.string()),
  }).index("by_athlete", ["athleteId", "start"]),
  analyses: defineTable({
    athleteId: v.id("athletes"),
    name: v.string(),
    query: v.any(),
    pinned: v.boolean(),
  }).index("by_athlete", ["athleteId"]),
  privacyZones: defineTable({
    athleteId: v.id("athletes"),
    name: v.string(),
    lat: v.number(),
    lon: v.number(),
    radius: v.number(),
  }).index("by_athlete", ["athleteId"]),
  shares: defineTable({
    athleteId: v.id("athletes"),
    token: v.string(),
    kind: v.string(),
    activityIds: v.array(v.id("activities")),
    fields: v.array(v.string()),
    expires: v.optional(v.number()),
    revoked: v.boolean(),
    createdAt: v.number(),
  })
    .index("by_token", ["token"])
    .index("by_athlete", ["athleteId"]),
  health: defineTable({
    athleteId: v.id("athletes"),
    date: v.string(),
    kind: v.string(),
    value: v.number(),
    source: v.string(),
    sourceId: v.optional(v.id("sources")),
    at: v.optional(v.number()),
    unit: v.optional(v.string()),
  }).index("by_athlete", ["athleteId", "date"]),
  billing: defineTable({
    athleteId: v.id("athletes"),
    customerId: v.string(),
    subscriptionId: v.optional(v.string()),
    status: v.string(),
    periodEnd: v.optional(v.number()),
    updatedAt: v.number(),
  })
    .index("by_athlete", ["athleteId"])
    .index("by_customer", ["customerId"]),
  webhookEvents: defineTable({ eventId: v.string(), at: v.number() }).index(
    "by_event",
    ["eventId"],
  ),
  outbox: defineTable({
    athleteId: v.id("athletes"),
    template: v.string(),
    dedupeKey: v.string(),
    status: v.string(),
    providerId: v.optional(v.string()),
    attempts: v.number(),
    createdAt: v.number(),
  })
    .index("by_athlete", ["athleteId"])
    .index("by_key", ["dedupeKey"])
    .index("by_provider", ["providerId"]),
  systemCounters: defineTable({ key: v.string(), count: v.number() }).index(
    "by_key",
    ["key"],
  ),
  usage: defineTable({
    athleteId: v.id("athletes"),
    kind: v.string(),
    window: v.string(),
    count: v.number(),
  }).index("by_athlete", ["athleteId", "kind", "window"]),
  messages: defineTable({
    athleteId: v.id("athletes"),
    role: v.string(),
    content: v.string(),
    evidence: v.optional(v.any()),
    at: v.number(),
  }).index("by_athlete", ["athleteId", "at"]),
  lifecycleJobs: defineTable({
    athleteId: v.id("athletes"),
    kind: v.string(),
    status: v.string(),
    key: v.optional(v.string()),
    error: v.optional(v.string()),
    createdAt: v.number(),
  }).index("by_athlete", ["athleteId"]),
});
